### ISSUE TITLE
Always insert state in stored states current and states goal.

### ISSUE THREAD

**Issue by azriel91** [azriel91/peace#138]
Currently serialized `states_current` and `states_goal` do not include entries for items whose `try_state_current` and `try_state_goal` return `None`.

~~Perhaps we should change `Item::try_state_*` to return a `State::Partial`.~~ maybe later

## Tasks

* [ ] `StatesSerde` should hold unknown entries (removed items).
* [ ] `States` should be mapped `From<StatesSerde>` after deserialization.
* [ ] Users should be informed when there are unknown entries.
* [ ] `States` should be mapped `Into<StatesSerde>`, with an entry for each item in the flow.
