### ISSUE TITLE
User friendly output on the command line - first cut

### ISSUE THREAD

**Issue by azriel91** [azriel91/peace#28]
The `CliOutput` currently serializes `StatesCurrent`, `StatesDesired`, and `StateDiffs` when output to the command line. The serialized output can be very verbose and difficult to take in at a glance, especially for flows with large numbers of `ItemSpec`s.

Improvements that can be made:

* [x] Single line output per `ItemSpec` state. Possibly a `TypeMap` that constrains values to implement `Display` (#37).
* [x] Colourized output. Maybe use `console` -- this is what `indicatif` uses, and we may use that for writing progress (#38).
* [x] `CliOutputFormatter` to toggle between single line vs serialized form (#39).
* [x] Confirm compatibility with [`miette::Diagnostic`](https://github.com/zkat/miette) (#40).

---

Random snippet for writing each item spec's state on a single line.

```rust
let stdout = &mut self.stdout;
stream::iter(states_current.iter())
    .map(Result::<_, E>::Ok)
    .try_fold(
        stdout,
        |stdout, (item_spec_id, _item_spec_state)| async move {
            stdout
                .write_all(item_spec_id.as_bytes())
                .await
                .map_err(Error::StdoutWrite)?;
            stdout.write_all(b": ").await.map_err(Error::StdoutWrite)?;
            // stdout.write_all(/* state */).await?;
            Ok(stdout)
        },
    )
    .await?;
```

**Comment by azriel91** [comment]
Splitting the remaining improvement work to a later issue. Namely:

* Refactor `Error` to consolidate all `State*Deserialize` and `Serialize` errors into a single variant.
* Specify diagnostic source code, spans, and help messages for each variant.
* Update *Cmds and tests to write errors to OutputWrite.
* Update `InMemoryTextOutput` for the web to display `miette` reports.
