### ISSUE TITLE
Replace `EnsureOpSpec` and `CleanOpSpec` with `ApplyOpSpec`

### ISSUE THREAD

**Issue by azriel91** [azriel91/peace#67]
The ensure and clean operations are the same "apply" logic, with the target state either being the desired state, or the cleaned state.

Peace is intended to be able to support a set of target states such as "an empty set of servers", e.g. reusing servers for testing installation of software. This means arbitrary target states for each item -- "desired state for items **a** and **b**, but cleaned state for item **c**".

This may include some support to model "defined state" and "clean state" as top level concepts which are currently captured as separate commands.

* [ ] As part of this, move `peace_core::progress` to `peace_cfg::resources`.

**Comment by azriel91** [comment]
### Tasks

* [x] Rename `EnsureOpSpec` to `ApplyOpSpec`.

    ```bash
    fd -Ftf 'ensure_op_spec' -x bash -c 'mv $0 ${0/ensure_op_spec/apply_op_spec}' {}
    sd -s 'ensure_op_spec' 'apply_op_spec' $(fd -tf)
    sd -s 'EnsureOpSpec' 'ApplyOpSpec' $(fd -tf)
    sd -s 'Ensure OpSpec' 'ApplyOpSpec' $(fd -tf)
    sd -s 'ensure_op' 'apply_op' $(fd -tf)
    sd -s 'ensure op' 'apply op' $(fd -tf)
    sd '/// (.+) apply_op_spec(.*)' '/// $1 apply op spec $2' $(fd -tf)
    cargo fmt --all
    ```

* [ ] Add `ItemSpec::state_clean` to return an example of an empty `State`.

    On naming, because we want to consolidate functions into one trait (#96), we will likely have the following names:

    ```rust
    trait ItemSpec {
        async fn state_clean();
        async fn state_current();
        async fn state_desired();

        async fn try_state_current();
        async fn try_state_desired();
    }
    ```

* [ ] Split `ApplyCmd` from `EnsureCmd`, and take in `target state`, which may be `state_desired` or `state_clean`.
* [ ] `EnsureCmd` and `CleanCmd` both delegate to `ApplyCmd`.
* [ ] Update item specs to move `CleanOpSpec` logic into `ApplyOpSpec`.
