### ISSUE TITLE
Cross-profile / cross-flow commands

### ISSUE THREAD

**Issue by azriel91** [azriel91/peace#81]
## What

In #80, in order to list profiles and a profile parameter, non-trivial code was written in the `app_cycle` example.

In addition, a lot of type parameters were introduced to the `CmdContext` type as the keys of the `*Params` type registries. This makes passing a `CmdContext` as a parameter noisy &ndash; as there are 6 type parameters and one lifetime parameter.

## Improvement

Make it easy to do the following:

* Workspace-wide aka cross-profile commands.

    - List all profiles &ndash; iterate over directories.
    - List all profiles and a particular profile parameter &ndash; load profile params.
    - List execution history for all profiles (for *write*-flows).
    - List execution history for specific profiles.

* Cross-profile-flow commands &ndash; still a workspace-wide command.

    - List all profiles' flow parameter for a particular flow.

* Profile-wide aka cross-flow commands.

    Not sure if there are any.

* `WorkspaceParams`, `ProfileParams`, and `FlowParams`' types must be specified, if they are to be deserialized.
* Notably, `ProfileParams` and `FlowParams` *may* be different for different profiles and flows. 

    If they are different, then it makes it impossible to deserialize them for a given `CmdContext`. We could constrain the params types to be a superset of all profile/flow params, which essentially is making them the same umbrella type.

    This should be feasible for `ProfileParams`, as profiles are intended to be logically separate copies of the same managed items. Production profiles may require more parameters, but the parameter type can be the same.

    However, `FlowParams` being different per flow is a fair assumption. This means cross profile inspections of the same flow is achievable -- the same `FlowParams` type and `ItemSpecGraph` can prepare the `TypeReg`istries to deserialize the `FlowParamsFile`, `StatesSavedFile`, and `StatesDesiredFile`.

* A `Profile` is needed when there are `ProfileParams` to store, as it is used to calculate the `ProfileDir` to store the params.
* A `FlowId` is needed when there are `FlowParams` to store, or an item spec graph to execute, as it is used calculate the `FlowDir` to store the params, or read or write `States`.
* You should be able to list profiles, read profile params, and list flows, without needing to have either a profile or a flow.
* For `States` from all flows to be deserializable, there must be a type registry with *all* item specs' `State` registered. This is a maintenance cost for implementors, but unavoidable if that kind of functionality is desired.

### Tasks

* [x] Extract `ParamsTypeRegs` to store `TypeReg<*ParamsK, BoxDt>`.
* [x] Change `CmdContext` to have `ItemSpecGraph` iff a `FlowId` is given. i.e. A `FlowId` is strictly linked to an ItemSpecGraph.
* [x] Change `CmdContext` to not require a `Profile`, but a `Profile` is necessary if a flow command is to be executed, i.e. when an `ItemSpecGraph` is provided.

    This means either:

    - Certain `*Cmd`s will only accept `CmdContext` when `CmdContext` has a `Profile` specified. Can use type state on the `CmdContext` type.
    - `*Cmd`s take in profile in their `exec` function.

    Other commands that are cross-profile will be one of:

    - Within the `Cmd`, an iteration over profiles, then execute the logic.
    - An iteration over profiles, and execute the `Cmd` for that profile.

**Comment by azriel91** [comment]
The `app_cycle` example `workspace init` command has:

* Workspace params:

    - URL to download
    - repo slug

* Flow states current and desired:

    - file download
    - tar extraction

Meaning, we need to store profile and flow parameters for the workspace init flow.

Should we have, instead of:

```
 app_cycle
├──  workspace_init
│   ├──  workspace_init
│   │   ├──  states_desired.yaml
│   │   └──  states_saved.yaml
│   └──  init.yaml
└──  init.yaml

```

```
 app_cycle
├──  workspace_params.yaml
├──  workspace_init_profile_params.yaml
├──  workspace_init_flow_params.yaml
├──  states_desired.yaml
└──  states_saved.yaml
```

It seems to be a lot more special casing. Perhaps we should just keep the current sentinel profile and flow values. We can rename the `init.yaml` files to `workspace_init.yaml`, `profile_init.yaml`, and `flow_init.yaml` to make it clearer what level each directory is at.
