### ISSUE TITLE
Referential item spec parameter values

### ISSUE THREAD

**Issue by azriel91** [azriel91/peace#94]
### What

Item spec parameter values are currently specified before a flow's execution.

Users should be able to specify that item spec parameter values should be looked up from values generated during execution.

### Notes

An idea on how to implement this is as follows:

1. Have the item spec params take in `T`.

    Derive a builder for the item spec params struct:

    - **Consumers:** When creating a flow and inserting flow params, call:

        ```rust
        ItemSpecParams::builder()
            .with_x("value")
            .with_x_ref::<T>()
            .with_x_from::<T, U>(|t| t.u())
            .build()
        ```

    - **Implementors:** For each field have a `with_x`, `with_x_ref::<T>()`, and `with_x_from::<T, U>(|t| -> U {})`

        ```rust
        #[derive(Params)]
        pub struct Params {
            /// ID of something generated.
            id_to_attach: String,
        }
        ```

    - **Peace:**

        1. Hold `&mut Resources` and insert `State`s into it as they are finished.
        2. Or should we use the existing Resources? -- likely, some things write to `W<'op, T>`
        3. Whenever we run an any function exec (state current / ensure op spec exec / etcetera all apply), we take `ItemSpec::Params`, and run `ItemSpecParamsBuilder::build_from(resources)`, which will use the static value / fetched and mapped values to return `ItemSpecParams`.
        4. Somehow that gets injected into the exec function -- not sure if we put a separate parameter whether that's nice or not, or if we can merge the `ItemSpecParams` type into the `Data`.

            Maybe instead of `W<'_, Params>`, we have a `P<'_, Params'>`, whose implementation does step 4.

        Still need to work out how to insert state into `Resources`. Do we silently include a `W<'_, State>` alongside every item spec's data writes? Maybe.

        ```rust
        params.fields()
            .iter()
            .map(|field_rt| field_rt.value(resources));

        impl FieldRt for Field<T, U> {
            fn fetch(resources: &Resources) -> Ref<'_, T> {
                match field {
                    FieldParam::Value(value) => value,
                    FieldParam::Ref => resources.borrow::<T>(),
                    FieldParam::From => {
                        let t = resources.borrow::<T>();
                        U::from(t)
                    }
                }
            }
        }
        ```
2. Then the item spec's data accessed includes `R<'op, T>` for data dependency calculation.

    1. Peace will take the `ItemSpecParamsBuilder`, figure out which fields are `ref`s / `from`s.
    2. Peace will fetch the `T` refs from `Resources`, and turn the builder into `ItemSpecParams` and ~~insert~~ write to it in `Resources`.

3. Item spec functions will be given the params with the values read from `Resources`.

    `ItemSpec`s' data must have a `Params<'_, ItemSpec::Params>` field in it to access the params.

---

## Design Thoughts

Is this too complicated, and people would just want to write a script to pass information between steps?

A process needs:

* Values / references for parameter values from the user
* Values generated by functions
* Transforming those values / references into flat values
* A way to pass the values between functions based on what was decided.

### User

* Uses `ParamsBuilder`, defines param values, or `ref`s / `from`s
* Uses `ItemSpec`, defines item spec IDs and params builder values.

### Item Spec Implementor

* Define `Params` -- what a user needs to pass in.
* Define runtime `Data`, e.g. `sdk::Client` -- other logic / data used during execution.
* Functions take in `Params`, `Data`, ctx, and state

```rust
fn state_clean              (params, data) -> Self::State;
fn state_current    (fn_ctx, params, data) -> Self::State;
fn try_state_current(fn_ctx, params, data) -> Self::State;
fn state_desired    (fn_ctx, params, data) -> Self::State;
fn try_state_desired(fn_ctx, params, data) -> Self::State;
fn state_diff               (params, data, state_a, state_b) -> Self::State;
fn check            (fn_ctx, params, data, state_current, state_desired, state_diff) -> Self::State;
fn apply_dry        (fn_ctx, params, data, state_current, state_desired, state_diff) -> Self::State;
fn apply            (fn_ctx, params, data, state_current, state_desired, state_diff) -> Self::State;
```

The function signature is quite long.

Grouping data and params in another layer may be a hassle, but may be a sensible decision if there will be a `fn_ctx` object provided to every function call.

Maybe the type for the `params` argument should be a generated type, with `Option` for each field -- wherever there is a `ref` or `from` value, the referenced value may not necessarily be available. Or maybe it should all be `Some`, and Peace should return an error / panic when a value cannot be resolved, except for `try_state_current` and `try_state_desired`, it may legitimately not be present.

Experiment:

* `state_clean`: Path to file(s) to clean up may be provided by predecessor.

    ```rust
    match params.file_paths() {
        Param::Value(file_paths) => {}
        Param::NotAvailable => {}
    }
    ```

    Does the `State`'s presentation need to have access to params, to output value? Perhaps not -- the params could have changed between creation of the item, and the presentation. So if the state should show a file path, then it should store it in the clean state.

* `state_current`: MD5 for remote file may not be available, if host IP is not available.

    ```rust
    match params.host_ip() {
        Param::Value(ip_address) => {}
        Param::NotAvailable => {}
    }
    ```

* `state_desired`: MD5 for file to upload may not be available, if file has not been downloaded.

    ```rust
    match params.file_path() {
        Param::Value(file_path) => {}
        Param::NotAvailable => {}
    }
    ```

If we group the `fn_ctx`, `params`, and `data` into the `FnCtx`, whereby the original `fn_ctx` may be empty, then the function signatures look like:

```rust
fn state_clean      (fn_ctx) -> Self::State;
fn state_current    (fn_ctx) -> Self::State;
fn try_state_current(fn_ctx) -> Self::State;
fn state_desired    (fn_ctx) -> Self::State;
fn try_state_desired(fn_ctx) -> Self::State;
fn state_diff       (fn_ctx, state_a, state_b) -> Self::State;
fn check            (fn_ctx, state_current, state_desired, state_diff) -> Self::State;
fn apply_dry        (fn_ctx, state_current, state_desired, state_diff) -> Self::State;
fn apply            (fn_ctx, state_current, state_desired, state_diff) -> Self::State;
```

Which looks cleaner; we have to make `FnCtx` generic, which adds a bit of mental load. Also, in code it doesn't just work as one `FnCtx<'_>` type -- `*Cmd`s need to pass in a type erased `FnCtx` for the progress sender (and later on more contextual information) -- i.e. no generics for `ItemSpec::Params` or `ItemSpec::Data` can be on the type, so a subset of `FnCtx` *could* be passed in from `*Cmd`, and the fuller `FnCtx` with `ItemSpec::Params` and `Data` augmented inside `ItemSpecWrapper`. This creates a web of types.

Perhaps the flat 6 parameters is more easily grasped, even if messy.

### Framework

* From `ItemSpec::Params`, define `ParamsBuilder`
* Maybe the type for the `params` argument should be a generated type, with `Option` for each field -- wherever there is a `ref` or `from` value, the referenced value may not necessarily be available. Or maybe it should all be `Some`, and Peace should return an error / panic when a value cannot be resolved, except for `try_state_current` and `try_state_desired`, it may legitimately not be present.

**Comment by azriel91** [comment]
## Tasks

* [ ] Insert `Option<ItemSpec::State>` before every flow execution.

    Known places where `Option<ItemSpecA::State>` is read are:

    - In `StatesCurrentDiscover` for `ItemSpecB`, in case item spec B's discovery uses item spec A's value for lookup.
    - In `StatesDesiredDiscover` for `ItemSpecB`, for item spec B to know what value should be used, for display or ensure.

    Where we need to write / save this in `Resources`:

    - After `StatesCurrentDiscover` for `ItemSpecA`
    - After `StatesDesiredDiscover` for `ItemSpecA`

* [ ] Maybe: In `ItemSpec`, split `Params` into a separate associated type.

    This allows the `Params` type to be constrained by a `Params` trait, by which Peace can expose `Params::Builder` to users, for when they have to construct params.

    This looks kind of verbose, but does the job:

    ```rust
    cmd_ctx_builder
        .with_flow_param_spec(
            "a".to_string(),
            ItemSpecAParams::spec().with_a1(A1::new("a1")),
        )
        .with_flow_param_spec(
            "b".to_string(),
            ItemSpecBParams::spec()
                .with_b1_ref::<A1, _>()
                .with_b2_from::<A2, _>(|a2| a2.b1().clone())
        )
        .await?;
    ```

    Can we make it less verbose? Options:

    - Don't require `ParamsKeys` for flow params, don't allow arbitrary params, automatically register all `ItemSpec::Params`.

        Still need params keys for workspace and profile parameters, which breaks consistency.

        How else can we not require registration for flow params?

    - ??

    Should the spec require every field to `impl FromStr`? That would make it easier for configuration based params -- need to serialize and deserialize the `ref/from` variants.


* [ ] Proc macro derive to create params spec builder for users.

    ```rust
    trait ItemSpec {
        /// Stuff read from Resources during execution.
        type Data: Data;
        /// Also read from Resources during execution,
        /// but the way to retrieve the values are specified by the user.
        type Params: Params;
    }

    trait Params { type Spec: ParamsSpec; }

    /// Automatically implemented when implementors `#[derive(Params)]` on their params type.
    impl Params for ItemSpecBParams {
        type Spec = ItemSpecBParamsSpec;
    }

    /// Automatically implemented when implementors `#[derive(Params)]` on their params type.
    ///
    /// These are interacted with by the user.
    struct ItemSpecBParamsSpec {
        /// One for each field in `ItemSpecBParams`
        t: ParamSpec<T>,
    }

    impl ItemSpecBParamsSpec {
        // For each field:
        fn with_t(self, t: T) -> Self;
        /// Note: this means the `T` field in B's params is the same type as `A::State`.
        fn with_t_ref(self) -> Self;
        fn with_t_from::<U, F>(self, f: F) -> Self
        where
            F: FnOnce(&U) -> T
        {
            self.t = ParamSpec::From(Box::new(move |resources| {
                let u = resources.borrow::<U>();
                f(u)
            }));

            self
        }
    }

    enum ParamSpec<T> {
        Value(T),
        Ref,
        From(Box<dyn Fn(&Resources) -> T>),
    }
    ```

**Comment by azriel91** [comment]
We need to raise an error when a `from_map` param spec is previously provided and stored, but not provided subsequently.

Options:

1. Resolve from:

    1. item_spec_rt
    2. params
    3. params_spec
    4. downcast
    5. match value_spec
    6. MappingFn::is_valued

2. Create a `BoxDtParamsSpec`, which enables:

    `params_spec.is_valid()`, which needs to be implemented for each
`ParamsSpec`.

3. Users register a `Map<K, function logic>`, but we still need to resolve
   `K`.

    Probably still need option 1 or 2 implemented then.

What about, every `Params` is recursive.

Every `Params` is resolved through a `ParamsSpec`, not just its fields, which
is closer to our current `ValueSpec`:

```rust
enum ValueSpec<T> {
    Stored,      // provided by loading file during context `build()`.
    Value(T),    // provided when defining context builder.
    From,        // provided by a predecessor at runtime.
    FromMap(..), // provided by a predecessor at runtime and mapped to the desired type.
    FieldWise {
        field_1: ValueSpec<F1>,
        field_2: ValueSpec<F2>,
    },
}
```
